# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d929a20116736911f567f7b34b9b1a8cbac09867100140ebc60572dcbdc5b234a4203be875ef6f231fcd7afa99c526819ef9ec4c2dd0c1cbfd19749f1ab6b9cb

test:
  secret_key_base: 8e0ec3825fdcd79323cab322028e618c54fdb3a4b005b105273ccaa9f6b36d258aece7b75654853a2f152ba0bafd2202f8e36cc02b1c89641d5e50c1740fd8a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
